default: &default
  adapter: sqlite3
  timeout: 5000

development:
  <<: *default
  database: sqlite3:project-name.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.pg
  adapter:  postgresql
  pool: 5
  timeout: 5000